#!/usr/bin/env python3
"""
session_end.py

Run at the END of every Manus development session.
Reports what was done to the Evolva Meta-Agent and persists the session
summary to manus-persistent-drive on GitHub.

Usage:
    python3 /home/ubuntu/meta-agent/session_end.py \
        --what "Built X, fixed Y, deployed Z" \
        --phase "Phase 143" \
        --blockers "Railway deploy failing on port binding" \
        --decisions "Use ChromaDB not pgvector for episodic memory" \
        --push  # push to GitHub

Or interactively (no args):
    python3 /home/ubuntu/meta-agent/session_end.py
"""

import os
import sys
import json
import time
import argparse
import subprocess
import requests

MANUS_API_KEY = os.environ.get("MANUS_API_KEY", "")
API_BASE = "https://api.manus.ai/v2"
AGENT_TASK_ID = "agent-default-main_task"
PERSISTENT_DRIVE = "/home/ubuntu/repos/manus-persistent-drive"

HEADERS = {
    "Content-Type": "application/json",
    "x-manus-api-key": MANUS_API_KEY,
}


def send_report(what_done: str, phase: str, blockers: list[str], decisions: list[str]) -> None:
    blockers_str = "\n".join(f"- {b}" for b in blockers) if blockers else "None"
    decisions_str = "\n".join(f"- {d}" for d in decisions) if decisions else "None"

    content = f"""SESSION END REPORT — {time.strftime('%Y-%m-%d %H:%M UTC')}

## What Was Done
{what_done}

## Current Phase
{phase}

## New Blockers
{blockers_str}

## New Locked Decisions
{decisions_str}

Please acknowledge this report and update your internal project state. Confirm:
1. The updated current phase
2. What the next session should focus on
3. Any consistency issues you detected in what was reported
"""

    resp = requests.post(
        f"{API_BASE}/task.sendMessage",
        headers=HEADERS,
        json={"task_id": AGENT_TASK_ID, "message": {"content": content}},
        timeout=30,
    )
    resp.raise_for_status()


def wait_for_ack(timeout: int = 60) -> str:
    deadline = time.time() + timeout
    while time.time() < deadline:
        resp = requests.get(
            f"{API_BASE}/task.listMessages",
            headers=HEADERS,
            params={"task_id": AGENT_TASK_ID, "order": "desc", "limit": 10},
            timeout=15,
        )
        resp.raise_for_status()
        messages = resp.json().get("messages", [])
        for msg in messages:
            if msg.get("type") == "status_update":
                status = msg.get("status_update", {}).get("agent_status")
                if status in ("stopped", "waiting"):
                    for m in messages:
                        if m.get("type") == "assistant_message":
                            return m.get("assistant_message", {}).get("content", "")
                    return "[Stopped with no message]"
        time.sleep(3)
    return "[Timeout]"


def save_to_persistent_drive(what_done: str, phase: str, blockers: list[str],
                              decisions: list[str], agent_ack: str) -> str:
    date_str = time.strftime("%Y-%m-%d")
    filename = f"sessions/session-{date_str}-auto.md"
    filepath = os.path.join(PERSISTENT_DRIVE, filename)

    os.makedirs(os.path.join(PERSISTENT_DRIVE, "sessions"), exist_ok=True)

    content = f"""# Session Report — {date_str}
*Auto-generated by session_end.py*

## What Was Done
{what_done}

## Phase
{phase}

## Blockers
{chr(10).join(f'- {b}' for b in blockers) if blockers else 'None'}

## Locked Decisions
{chr(10).join(f'- {d}' for d in decisions) if decisions else 'None'}

## Meta-Agent Acknowledgement
{agent_ack}
"""

    with open(filepath, "w") as f:
        f.write(content)

    return filepath


def push_to_github(filepath: str, pat: str = "") -> bool:
    """Commit and push the session report to manus-persistent-drive."""
    try:
        env = os.environ.copy()
        if pat:
            # Set up credentials temporarily
            cred_file = "/tmp/.git-credentials-tmp"
            with open(cred_file, "w") as f:
                f.write(f"https://Gudmundur76:{pat}@github.com\n")
            os.chmod(cred_file, 0o600)
            env["GIT_CONFIG_COUNT"] = "1"
            env["GIT_CONFIG_KEY_0"] = "credential.helper"
            env["GIT_CONFIG_VALUE_0"] = f"store --file={cred_file}"

        subprocess.run(
            ["git", "config", "user.email", "manus-agent@manus.im"],
            cwd=PERSISTENT_DRIVE, env=env, check=True, capture_output=True
        )
        subprocess.run(
            ["git", "config", "user.name", "Manus Agent"],
            cwd=PERSISTENT_DRIVE, env=env, check=True, capture_output=True
        )
        subprocess.run(
            ["git", "add", filepath],
            cwd=PERSISTENT_DRIVE, env=env, check=True, capture_output=True
        )
        result = subprocess.run(
            ["git", "diff", "--staged", "--quiet"],
            cwd=PERSISTENT_DRIVE, env=env, capture_output=True
        )
        if result.returncode == 0:
            print("Nothing to commit.")
            return True

        subprocess.run(
            ["git", "commit", "-m", f"session: auto-report {time.strftime('%Y-%m-%d')} [skip ci]"],
            cwd=PERSISTENT_DRIVE, env=env, check=True, capture_output=True
        )

        remote = "https://github.com/Gudmundur76/manus-persistent-drive.git"
        if pat:
            remote = f"https://Gudmundur76:{pat}@github.com/Gudmundur76/manus-persistent-drive.git"

        subprocess.run(
            ["git", "push", remote, "HEAD:main"],
            cwd=PERSISTENT_DRIVE, env=env, check=True, capture_output=True
        )

        if pat and os.path.exists(cred_file):
            os.remove(cred_file)

        return True
    except subprocess.CalledProcessError as e:
        print(f"Git push failed: {e.stderr.decode() if e.stderr else str(e)}")
        return False


def interactive_prompt() -> tuple[str, str, list[str], list[str]]:
    print("\n=== Evolva Meta-Agent Session End Report ===\n")
    what_done = input("What was done this session? (brief summary)\n> ").strip()
    phase = input("Current phase (e.g. 'Phase 143 — evolva-mragent build')?\n> ").strip()

    print("Blockers (one per line, empty line to finish):")
    blockers = []
    while True:
        b = input("  > ").strip()
        if not b:
            break
        blockers.append(b)

    print("New locked decisions (one per line, empty line to finish):")
    decisions = []
    while True:
        d = input("  > ").strip()
        if not d:
            break
        decisions.append(d)

    return what_done, phase, blockers, decisions


def main():
    parser = argparse.ArgumentParser(description="Report session end to Evolva Meta-Agent")
    parser.add_argument("--what", default="", help="What was done this session")
    parser.add_argument("--phase", default="", help="Current phase")
    parser.add_argument("--blockers", nargs="*", default=[], help="New blockers")
    parser.add_argument("--decisions", nargs="*", default=[], help="New locked decisions")
    parser.add_argument("--push", action="store_true", help="Push session report to GitHub")
    parser.add_argument("--pat", default="", help="GitHub PAT for push (optional)")
    args = parser.parse_args()

    # Interactive if no args provided
    if not args.what:
        what_done, phase, blockers, decisions = interactive_prompt()
    else:
        what_done = args.what
        phase = args.phase
        blockers = args.blockers
        decisions = args.decisions

    print("\nSending session report to meta-agent...")
    send_report(what_done, phase, blockers, decisions)

    print("Waiting for acknowledgement...")
    ack = wait_for_ack(60)
    print(f"\nMeta-Agent: {ack[:500]}\n")

    # Save to persistent drive
    filepath = save_to_persistent_drive(what_done, phase, blockers, decisions, ack)
    print(f"Session report saved: {filepath}")

    # Push to GitHub if requested
    if args.push or args.pat:
        pat = args.pat or os.environ.get("GITHUB_PAT", "")
        if pat:
            success = push_to_github(filepath, pat)
            if success:
                print("Session report pushed to GitHub.")
            else:
                print("Push failed. Report is saved locally.")
        else:
            print("No PAT provided. Skipping GitHub push.")
            print(f"To push manually: cd {PERSISTENT_DRIVE} && git add {filepath} && git commit -m 'session report' && git push")


if __name__ == "__main__":
    main()
